apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jaeger.fullname" . }}
  labels:
    app: {{ template "jaeger.name" . }}
    chart: {{ template "jaeger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: jaeger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "jaeger.name" . }}
      release: {{ .Release.Name }}
      component: jaeger
  template:
    metadata:
      labels:
        app: {{ template "jaeger.name" . }}
        release: {{ .Release.Name }}
        component: jaeger
    spec:
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: jaeger
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- range $key, $val := .Values.config.env }}
          - name: {{ $key | quote}}
            value: {{ $val | quote }}
        {{- end }}
        args:
          - "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json"
        {{- range .Values.config.args }}
          - {{ . | quote }}
        {{- end }}
        ports:
          # Agent ports
          - name: a-compact
            containerPort: 6831
            protocol: UDP
          - name: a-binary
            containerPort: 6832
            protocol: UDP
          - name: a-config
            containerPort: 5778
            protocol: TCP
          # Query ports
          - name: q-http
            containerPort: 16686
            protocol: TCP
          # Collector ports
          - name: c-grpc
            containerPort: 14250
            protocol: TCP
          - name: c-tchannel
            containerPort: 14267
            protocol: TCP
          - name: c-http-thrift
            containerPort: 14268
            protocol: TCP
        readinessProbe:
          httpGet:
            path: "/"
            port: 14269
          initialDelaySeconds: 5
