apiVersion: v1
kind: Service
metadata:
  name: {{ template "jaeger.fullname" . }}-collector
  labels:
    app: {{ template "jaeger.name" . }}
    chart: {{ template "jaeger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: jaeger
spec:
  type: {{ .Values.service.collector.type }}
  selector:
    app: {{ template "jaeger.name" . }}
    release: {{ .Release.Name }}
    component: jaeger
  ports:
    - name: grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: http-thrift
      port: 14268
      protocol: TCP
      targetPort: 14268
