dependencies:
  # Metrics
  - name: "influxdb"
    version: 1.1.4
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "grafana"
    version: 1.14.8
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/

  # Tracing
  - name: "jaeger"
    version: 0.0.4
    condition: swarm.tracingEnabled
    repository: https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/
