dependencies:
  # Blockchain
  - name: "ganache"
    version: 0.0.1
    condition: swarm.ganacheEnabled
    repository: https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/
  # Metrics
  - name: "influxdb"
    version: 1.3.2
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "kapacitor"
    version: 1.1.1
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "kapacitor-importer"
    version: 0.0.1
    condition: swarm.metricsEnabled
    repository: https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/
  - name: "grafana"
    version: 3.8.3
    condition: swarm.metricsEnabled
    repository: https://kubernetes-charts.storage.googleapis.com/

  # Tracing
  - name: "jaeger"
    version: 0.0.8
    condition: swarm.tracingEnabled
    repository: https://raw.githubusercontent.com/ethersphere/helm-charts-artifacts/master/
