{{- $root := . -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "smoke.fullname" $root }}-smoke
  labels:
    app: {{ template "smoke.name" $root }}
    chart: {{ template "smoke.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ $root.Values.smoke.schedule }}"
  successfulJobsHistoryLimit: {{ $root.Values.smoke.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $root.Values.smoke.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ $root.Values.smoke.concurrencyPolicy | quote }}
  jobTemplate:
    metadata:
      labels:
        app: {{ template "smoke.name" $root }}
        chart: {{ template "smoke.chart" . }}
        release: {{ .Release.Name }}
    spec:
      template:
        metadata:
          labels:
            app: {{ template "smoke.name" $root }}
            chart: {{ template "smoke.chart" . }}
            release: {{ .Release.Name }}
        spec:
          containers:
          - name: smoke
            image: {{ .Values.smoke.image.repository }}:{{ .Values.smoke.image.tag }}
            imagePullPolicy: {{ .Values.smoke.imagePullPolicy | quote }}
            command: ["/run-smoke.sh"]
            resources:
{{ toYaml .Values.smoke.resources | indent 14 }}
            args:
            - --hosts={{- range $i, $e := until (int $root.Values.smoke.config.swarmReplicas) }}{{if ne $i 0}},{{end}}{{ $root.Values.smoke.config.prefix }}-{{ $i }}.{{ $root.Values.smoke.config.suffix }}{{- end }}
            - --verbosity=5
            - --metrics
            - --metrics.influxdb.endpoint={{ .Values.smoke.config.influxdbEndpoint }}
            - --metrics.influxdb.username={{ .Values.smoke.config.influxdbUsername }}
            - --metrics.influxdb.password={{ .Values.smoke.config.influxdbPassword }}
            - --metrics.influxdb.database=metrics
            - --metrics.influxdb.tags=host={{ .Values.smoke.config.name }}
{{- range $i, $flag := .Values.smoke.config.extraFlags }}
            - {{ $flag }}
{{- end }}
            - {{ .Values.smoke.config.operation }}
          restartPolicy: Never
