apiVersion: v1
kind: Secret
metadata:
  name: {{ template "swarm.fullname" . }}-bootnode
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: bootnode
type: Opaque
data:
  bootnode.key: {{ .Values.bootnode.config.nodekey | b64enc | quote }}
  bzzaccount.password: {{ .Values.swarm.secrets.password | b64enc | quote }}
