apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "swarm.fullname" . }}-podflags
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.swarm.config.podSpecificFlags }}
  {{ $key | lower }}: {{ $value }}
{{- end }}