{{- if .Values.bootnode.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "swarm.fullname" . }}-bootnode
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: bootnode
spec:
  selector:
    app: {{ template "swarm.name" . }}
    release: {{ .Release.Name }}
    component: bootnode
  clusterIP: None
  ports:
  - name: network
    port: 30399
{{- end }}
