apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: {{ template "swarm.fullname" . }}
  labels:
    app: {{ template "swarm.name" . }}
    chart: {{ template "swarm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  PASSWORD: {{ .Values.swarm.secrets.password | b64enc | quote }}
